
services:
  db:
    image: postgres:15
    container_name: etl_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwort123
      POSTGRES_DB: etl_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
